#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="$ROOT_DIR/output/research-loop-vybe-demo"
mkdir -p "$OUT_DIR"

if [[ -z "${VYBE_AGENT:-}" ]]; then
  echo "VYBE_AGENT is required" >&2
  exit 2
fi

PROJECT_ARG=""
PROMPT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      PROJECT_ARG="$2"
      shift 2
      ;;
    -p)
      PROMPT="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

rid() {
  printf '%s_%s_%s' "$1" "$(date +%s%N)" "$RANDOM"
}

BRIEF_JSON="$(vybe resume --agent "$VYBE_AGENT" --peek)"
TASK_ID="$(echo "$BRIEF_JSON" | jq -r '.data.brief.task.id // ""')"
TITLE="$(echo "$BRIEF_JSON" | jq -r '.data.brief.task.title // ""')"
DESC="$(echo "$BRIEF_JSON" | jq -r '.data.brief.task.description // ""')"

if [[ -z "$TASK_ID" ]]; then
  exit 0
fi

vybe push \
  --agent "$VYBE_AGENT" \
  --request-id "$(rid log_start)" \
  --json "{\"task_id\":\"$TASK_ID\",\"event\":{\"kind\":\"research_started\",\"message\":\"Starting mock research pass for: $TITLE\"}}" >/dev/null

vybe memory set \
  --agent "$VYBE_AGENT" \
  --request-id "$(rid mem_progress)" \
  --key checkpoint \
  --value "searched_local_catalog" \
  --scope task \
  --scope-id "$TASK_ID" >/dev/null

ARTIFACT_PATH="$OUT_DIR/${TASK_ID}.md"
cat >"$ARTIFACT_PATH" <<EOF
# Research Note

- task_id: $TASK_ID
- title: $TITLE
- project_arg: ${PROJECT_ARG:-none}
- workflow: local-first simulated
- prompt_bytes: ${#PROMPT}

## Observation

This is a demo artifact generated by the mock research worker.

## Description Snapshot

$DESC
EOF

vybe push \
  --agent "$VYBE_AGENT" \
  --request-id "$(rid artifact)" \
  --json "{\"task_id\":\"$TASK_ID\",\"artifacts\":[{\"file_path\":\"$ARTIFACT_PATH\"}]}" >/dev/null

if [[ "$TITLE" == *"BLOCKED_DEMO"* ]]; then
  vybe task complete \
    --agent "$VYBE_AGENT" \
    --request-id "$(rid status_block)" \
    --id "$TASK_ID" \
    --outcome blocked \
    --blocked-reason "Source type not available in demo mode" \
    --summary "Blocked: requires unavailable source" >/dev/null

  exit 0
fi

vybe push \
  --agent "$VYBE_AGENT" \
  --request-id "$(rid log_done)" \
  --json "{\"task_id\":\"$TASK_ID\",\"event\":{\"kind\":\"research_finished\",\"message\":\"Completed mock research pass and attached artifact\"}}" >/dev/null

vybe task complete \
  --agent "$VYBE_AGENT" \
  --request-id "$(rid status_done)" \
  --id "$TASK_ID" \
  --outcome done \
  --summary "Mock research pass completed" >/dev/null
