#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="$ROOT_DIR/output/research-loop-vibe-demo"
mkdir -p "$OUT_DIR"

if [[ -z "${VIBE_AGENT:-}" ]]; then
  echo "VIBE_AGENT is required" >&2
  exit 2
fi

PROJECT_ARG=""
PROMPT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      PROJECT_ARG="$2"
      shift 2
      ;;
    -p)
      PROMPT="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

rid() {
  printf '%s_%s_%s' "$1" "$(date +%s%N)" "$RANDOM"
}

BRIEF_JSON="$(vibe brief --agent "$VIBE_AGENT")"
TASK_ID="$(echo "$BRIEF_JSON" | jq -r '.data.brief.task.id // ""')"
TITLE="$(echo "$BRIEF_JSON" | jq -r '.data.brief.task.title // ""')"
DESC="$(echo "$BRIEF_JSON" | jq -r '.data.brief.task.description // ""')"

if [[ -z "$TASK_ID" ]]; then
  exit 0
fi

vibe log \
  --agent "$VIBE_AGENT" \
  --request-id "$(rid log_start)" \
  --kind research_started \
  --task "$TASK_ID" \
  --msg "Starting mock research pass for: $TITLE" >/dev/null

vibe memory set \
  --agent "$VIBE_AGENT" \
  --request-id "$(rid mem_progress)" \
  --key checkpoint \
  --value "searched_local_catalog" \
  --scope task \
  --scope-id "$TASK_ID" >/dev/null

ARTIFACT_PATH="$OUT_DIR/${TASK_ID}.md"
cat >"$ARTIFACT_PATH" <<EOF
# Research Note

- task_id: $TASK_ID
- title: $TITLE
- project_arg: ${PROJECT_ARG:-none}
- workflow: local-first simulated
- prompt_bytes: ${#PROMPT}

## Observation

This is a demo artifact generated by the mock research worker.

## Description Snapshot

$DESC
EOF

vibe artifact add \
  --agent "$VIBE_AGENT" \
  --request-id "$(rid artifact)" \
  --task "$TASK_ID" \
  --path "$ARTIFACT_PATH" \
  --type text/markdown >/dev/null

if [[ "$TITLE" == *"BLOCKED_DEMO"* ]]; then
  vibe log \
    --agent "$VIBE_AGENT" \
    --request-id "$(rid log_block)" \
    --kind research_blocked \
    --task "$TASK_ID" \
    --msg "Blocked: requires source type not available in demo mode" >/dev/null

  vibe task set-status \
    --agent "$VIBE_AGENT" \
    --request-id "$(rid status_block)" \
    --id "$TASK_ID" \
    --status blocked >/dev/null

  exit 0
fi

vibe log \
  --agent "$VIBE_AGENT" \
  --request-id "$(rid log_done)" \
  --kind research_finished \
  --task "$TASK_ID" \
  --msg "Completed mock research pass and attached artifact" >/dev/null

vibe task set-status \
  --agent "$VIBE_AGENT" \
  --request-id "$(rid status_done)" \
  --id "$TASK_ID" \
  --status completed >/dev/null
